[staging]
test01.example.com ansible_user=admin
test02.example.com ansible_user=admin

[staging:vars]
# На staging можно делать авто-ребут для тестов
auto_reboot=true
update_level=security
ansible_python_interpreter=/usr/bin/python3
